site_name: SQL Introduction
nav:
  - Home: "index.md"
  - Introduction to SQL: "SQLintroduction.md"
  - DDL: "DDL.md"
  - DML: "DML.md"
  - DQL: "DQL.md"
  - Troubleshooting: "troubleshooting.md"
  - Glossary: "glossary.md"

theme:
  name: material

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: lime
      accent: teal
      toggle:
        icon: material/weather-night
        name: Light mode

  language: en
  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.sections
    - navigation.top
    - navigation.footer
    - toc.integrate
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true



